### PR TITLE
feat(format): add markdown support

### PR DESCRIPTION
**Pull request by tete2soja**
Hello,

It will solve the issue I opened previously for it: https://github.com/pixelfactoryio/privatebin-cli/issues/39.

Happy to fix it my self and share with you!

### CODE REVIEW

**Comment by amine7536** [comment]
Hi @tete2soja, many thanks for your contribution 🙂

Can you add validation for the `--textformat` option ? I guess nnly allowed values should be `plaintext` and `markdown`. You can do it using a "coercion" function. You can use the `--expire` option for example : https://github.com/pixelfactoryio/privatebin-cli/blob/master/src/cmd/send.ts#L30

**Comment by tete2soja** [comment]
Ok! I will add this to check correct value is set and push back the fix :)

**Comment by flying-sausages** [comment]
I think another allowed value should be `sourcecode`?

afbeelding

Would appreciate this upstream :)

**Comment by tete2soja** [comment]
I will take a look asap since we can also specify the source code language.
Have a nice end of year :tada:

**Comment by flying-sausages** [comment]
Nice! would it be more comfortable to do that in a separate PR for smaller review scopes?

**Pull request merged**
